/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-error-container": "#93000a",
        "surface-bright": "#f8f9fa",
        "on-secondary-fixed": "#00201a",
        "tertiary-fixed": "#ffdad6",
        "tertiary": "#500004",
        "secondary": "#006b5a",
        "secondary-fixed": "#87f6dc",
        "inverse-surface": "#2e3132",
        "surface-container-highest": "#e1e3e4",
        "on-primary-container": "#96a4b7",
        "background": "#f8f9fa",
        "inverse-on-surface": "#f0f1f2",
        "on-surface-variant": "#44474c",
        "on-surface": "#191c1d",
        "secondary-container": "#84f3d9",
        "on-background": "#191c1d",
        "on-tertiary-fixed-variant": "#93000d",
        "on-secondary-fixed-variant": "#005143",
        "surface": "#f8f9fa",
        "primary": "#172434",
        "on-tertiary-fixed": "#410002",
        "on-primary-fixed": "#0f1c2b",
        "on-error": "#ffffff",
        "outline": "#74777d",
        "on-tertiary": "#ffffff",
        "error": "#ba1a1a",
        "on-secondary-container": "#00705e",
        "tertiary-container": "#790008",
        "tertiary-fixed-dim": "#ffb4ab",
        "inverse-primary": "#bac8dc",
        "primary-container": "#2d3a4a",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#bac8dc",
        "secondary-fixed-dim": "#69d9c0",
        "error-container": "#ffdad6",
        "outline-variant": "#c4c6cc",
        "on-primary-fixed-variant": "#3b4858",
        "surface-dim": "#d9dadb",
        "surface-variant": "#e1e3e4",
        "surface-container-high": "#e7e8e9",
        "on-tertiary-container": "#ff7a6f",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "primary-fixed": "#d6e4f8",
        "surface-tint": "#525f71",
        "surface-container": "#edeeef",
        "surface-container-low": "#f3f4f5"
      },
      fontFamily: {
        "headline": ["Inter", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
